Evaluator
ivan-chai/unsupervised-pretraining pull request #1
Opened 2021-11-12 15:39 UTC by BerAnton

Оценщик для тренировка на размеченных данных.

Исопльзовал Hydra, т.к. показалось, что в дальнейшем будет проще добавлять новые модельки и их быстро конфигурировать.

В models лежит пример того, как добавлять веса моделей и проверочный эмбеддинг для проверки. Т.к. мне никто так и не скинул свой эмбеддеры, то взял заджитованный resnet18.
Все конфиги лежат в src/ulib/configs.

В dataset лежат первые 16 элементов неразмеченной части датасета, чтобы при тренировке головы не приходилось в память подтягивать всю неразмеченную часть датасета.

В README.md кратко описал как добавлять новую модель и как запускать оценщик.

2021-11-15 13:28 UTC, ivan-chai commented
Не стоит бинарники в git коммитить. Замедляет чекаут, работу с ветками, усложнаяет диффы и ревью. Для таких вещей обычно или внешние хранилища используют или git-lfs. Для бинарников лучше яндекс диск заведем.

2021-11-15 14:02 UTC, ivan-chai requested changes
Вцелом пожелание отделить конфиги оценщика, чтобы не путались с моделями, и бинари залить в облако.

2021-11-15 14:02 UTC, ivan-chai commented on README.md
> +pip install -e .
Или ./unsupervsied-pretraining?

2021-11-15 14:02 UTC, ivan-chai commented on README.md
> +src/ulib/configs/model/.
Немного странно, что конфиги и модели лежат в разных, заранее определенных местах. Почему бы просто не передавать путь до папки, где и веса и конфиги и эмбеддинги? Я согласен, что финальные конфиги нужно закоммитить в репу, но так репозиторий превращается еще и в рабочую папку. Код путается с данными, проблемы с чекаутами и т.п.

2021-11-15 14:02 UTC, ivan-chai commented on README.md
> +ulib_train
Нужно как-то выбирать модель для оценки.

2021-11-15 14:02 UTC, ivan-chai commented on src/ulib/configs/callbacks/default.yaml
> +early_stopping:
По пути к файлу не понятно, что это конфиг оценщика. Кажется, что сама модель учится. Оценщик это независимая часть репы.

2021-11-15 14:02 UTC, ivan-chai commented on src/ulib/data/stl10.py
> +
Докстринга с описанием датасета и путем для скачивания данных.

2021-11-15 14:02 UTC, ivan-chai commented on src/ulib/data/stl10.py
> +    def __init__(self, data_dir: str = "./dataset", batch_size: int = 32, num_workers: int = 4):
Хардкод. Путь до данных лучше всегда передавать.

2021-11-15 14:02 UTC, ivan-chai commented on src/ulib/data/stl10.py
> +    def __init__(self, data_dir: str = "./dataset", batch_size: int = 32, num_workers: int = 4):
Питон динамически типизируемый язык. Зачем type annotations?

2021-11-15 14:02 UTC, ivan-chai commented on src/ulib/data/stl10.py
> +
Зачем пустые строки после заголовка? Пустое место помогает структурировать большие куски кода, вроде абзацев. Но сильно много пустых строк усложняет чтение, т.к. меньше помещается на экране.

2021-11-15 14:02 UTC, ivan-chai commented on src/ulib/model/classification.py
> +
Перед return тоже не понятно, зачем пустые строки.

2021-11-15 14:02 UTC, ivan-chai commented on src/ulib/scripts/train.py
> +    trainer.test(model, data)
Долго обучение занимает? Если не очень, можно хоть 5 сидов прогнать и mean/std вывести.

2021-11-15 14:02 UTC, ivan-chai commented on tests/conftest.py
> +# TODO: сделать фикстуры для каждой модели. Вследствие их отсутствия тут resnet18
Комменты это предложения на естественном языке. Заканчиваются точкой.

2021-11-15 14:02 UTC, ivan-chai commented on tests/test_model.py
> +    # пока что здесь resnet18, у Влада эмбеддер всего лишь после двух эпох. Потом можно изменить.
Начинаются комменты с большой буквы.

2021-11-16 11:47 UTC, BerAnton commented
Сделал изменения согласно замечаниям.
Протестировал загрузку моделек/эмбеддингов с яндекс диска.

2021-11-16 13:19 UTC, ivan-chai commented
Оценщик для тренировка на размеченных данных.

Исопльзовал Hydra, т.к. показалось, что в дальнейшем будет проще добавлять новые модельки и их быстро конфигурировать.

В models лежит пример того, как добавлять веса моделей и проверочный эмбеддинг для проверки. Т.к. мне никто так и не скинул свой эмбеддеры, то взял заджитованный resnet18.
Все конфиги лежат в src/ulib/configs.

В dataset лежат первые 16 элементов неразмеченной части датасета, чтобы при тренировке головы не приходилось в память подтягивать всю неразмеченную часть датасета.

В README.md кратко описал как добавлять новую модель и как запускать оценщик.

2021-11-16 13:19 UTC, merged